# Generated by Django 5.2.4 on 2025-08-11 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('description', models.CharField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Пример',
                'verbose_name_plural': 'Примеры',
                'db_table': 'Examples',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ListImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='examples.examples', verbose_name='Пример')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'db_table': 'ListImages',
                'managed': True,
            },
        ),
    ]
