# Generated by Django 5.2.4 on 2025-08-11 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examples',
            options={'verbose_name': 'Пример', 'verbose_name_plural': 'Примеры'},
        ),
        migrations.AlterModelOptions(
            name='listimages',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='listimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='examples_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='examples',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='examples',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='listimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='examples.examples', verbose_name='Пример работы'),
        ),
        migrations.AlterModelTable(
            name='examples',
            table=None,
        ),
        migrations.AlterModelTable(
            name='listimages',
            table=None,
        ),
    ]
