# Generated by Django 5.2.4 on 2025-07-12 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_subcategories_products_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.categories', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='ProductRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_products', to='goods.products')),
                ('to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_products', to='goods.products')),
            ],
            options={
                'unique_together': {('from_product', 'to_product')},
            },
        ),
        migrations.AddField(
            model_name='products',
            name='related_products',
            field=models.ManyToManyField(blank=True, through='goods.ProductRelationship', through_fields=('from_product', 'to_product'), to='goods.products', verbose_name='Сопутствующие товары'),
        ),
    ]
