# Generated by Django 5.2.4 on 2025-07-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_subcategories_category_productrelationship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(choices=[('Без покраски', 'Без покраски'), ('Белый глянец', 'Белый глянец'), ('Черный мал.', 'Черный мал.'), ('Белый муар', 'Белый муар'), ('Черный муар', 'Черный муар')], default='Без покраски', max_length=50, verbose_name='Цвет детали'),
        ),
    ]
