# Generated by Django 5.2.4 on 2025-07-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_products_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, choices=[('Без покраски', 'Без покраски'), ('Белый глянец', 'Белый глянец'), ('Черный мал.', 'Черный мал.'), ('Белый муар', 'Белый муар'), ('Черный муар', 'Черный муар')], default=False, max_length=50, null=True, verbose_name='Цвет детали'),
        ),
    ]
