# Generated by Django 5.2.4 on 2025-07-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_alter_products_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, choices=[('2м.', '2м.'), ('2,2м.', '2,2м.'), ('2,5м.', '2,5м.'), ('3м.', '3м.'), ('3.2м.', '3.2м.'), ('3.6м.', '3.6м.'), ('3м.', '3м.'), ('2000 мм.', '2000 мм.')], max_length=30, null=True, verbose_name='Размер детали'),
        ),
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, choices=[('Без покраски', 'Без покраски'), ('Белый глянец', 'Белый глянец'), ('Черный мал.', 'Черный мал.'), ('Белый муар', 'Белый муар'), ('Черный муар', 'Черный муар')], max_length=30, null=True, verbose_name='Цвет детали'),
        ),
    ]
