# Generated by Django 5.2.4 on 2025-07-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_products_size_alter_products_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='count_in_puck',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('4', '4'), ('5', '5'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('16', '16'), ('20', '20'), ('25', '25'), ('40', '40'), ('50', '50')], max_length=30, null=True, verbose_name='Количество в упак.'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
