# Generated by Django 5.2.4 on 2025-07-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_products_count_in_puck_alter_products_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('name', 'color', 'size'), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='products',
            name='image_schem',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images_schems', verbose_name='Изображение_схемы'),
        ),
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, choices=[('Без покраски', 'Без покраски'), ('Белый глянец', 'Белый глянец'), ('Белый мат.', 'Белый мат.'), ('Черный мат.', 'Черный мат.'), ('Белый муар', 'Белый муар'), ('Черный муар', 'Черный муар')], max_length=30, null=True, verbose_name='Цвет детали'),
        ),
        migrations.AlterField(
            model_name='products',
            name='count_in_puck',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('16', '16'), ('20', '20'), ('25', '25'), ('40', '40'), ('50', '50')], max_length=30, null=True, verbose_name='Количество в упак.'),
        ),
    ]
