# Generated by Django 5.2.4 on 2025-07-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_alter_products_options_products_image_schem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='count_in_puck',
        ),
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, choices=[('Без покраски', 'Без покраски'), ('Белый', 'Белый'), ('Черный', 'Черный'), ('Белый глянец', 'Белый глянец'), ('Белый мат.', 'Белый мат.'), ('Черный мат.', 'Черный мат.'), ('Белый муар', 'Белый муар'), ('Черный муар', 'Черный муар')], max_length=30, null=True, verbose_name='Цвет детали'),
        ),
    ]
