# Generated by Django 5.2.4 on 2025-07-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_products_count_in_puck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='count_in_puck',
        ),
    ]
