# Generated by Django 5.2.4 on 2025-07-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_remove_products_count_in_puck'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='bright',
            field=models.CharField(blank=True, choices=[('3000K', '3000K'), ('4000K', '4000K')], max_length=30, null=True, verbose_name='Яркость'),
        ),
        migrations.AddField(
            model_name='products',
            name='power',
            field=models.CharField(blank=True, choices=[('6W', '6W'), ('10W', '10W'), ('12W', '12W'), ('18W', '18W'), ('20W', '20W'), ('30W', '30W'), ('40W', '40W')], max_length=30, null=True, verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, choices=[('2м.', '2м.'), ('2,2м.', '2,2м.'), ('2,5м.', '2,5м.'), ('3м.', '3м.'), ('3.2м.', '3.2м.'), ('3.6м.', '3.6м.'), ('3м.', '3м.'), ('2000 мм.', '2000 мм.'), ('40x40', '40x40'), ('60x40', '60x40'), ('120x80', '120x80')], max_length=30, null=True, verbose_name='Размер детали'),
        ),
    ]
