# Generated by Django 5.2.4 on 2025-07-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_products_bright_products_power_alter_products_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='power',
            field=models.CharField(blank=True, choices=[('6W', '6W'), ('9W', '9W'), ('10W', '10W'), ('12W', '12W'), ('18W', '18W'), ('20W', '20W'), ('24W', '24W'), ('30W', '30W'), ('40W', '40W')], max_length=30, null=True, verbose_name='Мощность'),
        ),
    ]
