# Generated by Django 5.2.4 on 2025-07-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_alter_products_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='bright',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Яркость K'),
        ),
        migrations.AlterField(
            model_name='products',
            name='power',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Мощность W'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Размер детали'),
        ),
    ]
