# Generated by Django 5.2.4 on 2025-07-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0018_alter_products_bright_alter_products_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=7, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.PositiveIntegerField(default=50, verbose_name='Количество'),
        ),
    ]
