# Generated by Django 5.2.4 on 2025-08-11 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0019_alter_products_price_alter_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, to='goods.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, choices=[('Без покраски', 'Без покраски'), ('Белый', 'Белый'), ('Черный', 'Черный'), ('Серебро', 'Серебро'), ('Серый', 'Серый'), ('Золотой', 'Золотой'), ('Белый глянец', 'Белый глянец'), ('Белый мат.', 'Белый мат.'), ('Черный мат.', 'Черный мат.'), ('Белый муар', 'Белый муар'), ('Черный муар', 'Черный муар')], max_length=30, null=True, verbose_name='Цвет детали'),
        ),
        migrations.AlterField(
            model_name='products',
            name='subcategory',
            field=models.ForeignKey(blank=True, default=28, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.subcategories', verbose_name='Подкатегория'),
        ),
    ]
