# Generated by Django 5.2.4 on 2025-07-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_processing', 'В обработке'), ('confirmed', 'Подтвержден'), ('in_delivery', 'В доставке'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='in_processing', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
