# Generated by Django 5.2.4 on 2025-07-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Подтвержден', 'Подтвержден'), ('В доставке', 'В доставке'), ('Завершен', 'Завершен'), ('Отменен', 'Отменен')], default='В обработке', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
